
server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smbms?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: ok
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false


mybatis:
  configuration:
    auto-mapping-behavior: full
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zb.demo3.entity
